spring:
  mail:
    host: smtp.gmail.com
    username: danielgonzalez5875@gmail.com
    password: gvvn xmkpp bxzc skr
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
